server:
  port: 8080

application:
  jwt:
    secretKey: SecureKeyMustBeLongEnoughForHS256AlgorithmOrLongerSoThisIsAnExampleSecureKeyMustBeLongEnoughForHS256AlgorithmOrLongerSoThisIsAnExample
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 7
spring:
  application:
    name: BarberShop
  jackson:
    default-property-inclusion: NON_NULL

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=A3NguyenVanAn_18D04;encrypt=true;trustServerCertificate=true;
    username: sa
    password: MichaelAn271
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
